version: '3.8'

services:
  users:
    build:
      context: .
      args:
        APP_NAME: users
    environment:
      - NODE_ENV=development
    networks:
      - internal
    restart: unless-stopped

  notifications:
    build:
      context: .
      args:
        APP_NAME: notifications
    environment:
      - NODE_ENV=development
    networks:
      - internal
    restart: unless-stopped

  orders:
    build:
      context: .
      args:
        APP_NAME: orders
    environment:
      - NODE_ENV=development
    depends_on:
      - users
      - notifications
    networks:
      - internal
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      args:
        APP_NAME: api-gateway
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - USERS_HOST=users
      - USERS_PORT=3001
      - ORDERS_HOST=orders
      - ORDERS_PORT=3002
      - NOTIFICATIONS_HOST=notifications
      - NOTIFICATIONS_PORT=3003
    depends_on:
      - users
      - orders
      - notifications
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge